### ISSUE TITLE
Tool tips do not disappear if you click and drag while they are open

### ISSUE THREAD

**Issue by mdaffin** [psifidotos/workflow-project#40]
**Reproduce**
- Hover over an element until its tool-tip shows
- Press the mouse button on the element
- Move the mouse to another location
- Release the mouse button

**Results**
The tool-tip does not disappear and so you can open multiple tool-tips at once
Hovering over the element again to trigger the tool-tip returns the function to normal.

**Expect result**
The tool-tip should disappear when the mouse leaves the element regardless of the state of the mouse button.

**Comment by mdaffin** [comment]
I have found that other elements suffer from this as well, anything that changes when you mouse over it.

This is due to the onExisted signal not properly firing if you drag the mouse out of the MouseArea. A better solution is to use the MouseArea.containsMouse with states to toggle the opacity.

I have started to convert to this method (partly as it made the code cleaner as well) in my qml-clean branch where I am also restructuring the qml code to be neater and simpler.

**Comment by psifidotos** [comment]
ok james but I think that with the last commit this is fixed....

**Comment by psifidotos** [comment]
james if you have a better solution for tooltips, no problem i will test it. DTooltip was created because the default tooltip from qml plasmacomponents had many issues. I dont know if that has changed in 4.9. Many elements are going to be removed totally in the future when qml plasma components mature enough. This is for Tooltips and Dialogs mainly....

**Comment by mdaffin** [comment]
I am working on restructuring the qml code now to tidy it up (on the qml-clean branch), tooltips was going to be one of the next components I look at once I have finished with the current component.

**Comment by mdaffin** [comment]
~~The bug is not fixed, it still occurs if you move the mouse out of the element before it is deleted. (cant see a way to reopen the issue)~~

~~Since this occurs mostly when you drag the window about your solution does not help much as you tend to move the mouse faster then the tooltip disappears.~~

~~I note that the add workarea button does not suffer from this, it disappears when you release the mouse.~~ I would not worry to much about this issue as I will be fixing it as I rework the qml code.

**Comment by mdaffin** [comment]
Opps sorry, had a stale build, this does fix the issue.
